[package]
name = "submerge-crystal"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
default-run = "submerge-crystal"

[[bin]]
name = "submerge-crystal"
path = "src/main.rs"

[[bin]]
name = "openapi-gen"
path = "src/generate_openapi.rs"

[dependencies]
anyhow = { workspace = true }
async-recursion = { workspace = true }
async-trait = { workspace = true }
axum = { workspace = true }
clap = { workspace = true }
convert_case = { workspace = true }
frame-metadata = { workspace = true }
frame-system = { workspace = true }
hex = { workspace = true }
lru = { workspace = true }
once_cell = { workspace = true }
paste = { workspace = true }
parity-scale-codec = { workspace = true }
reqwest = { workspace = true }
rustc-hash = { workspace = true }
scale-decode = { workspace = true }
scale-info = { workspace = true }
scale-type-resolver = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sp-core = { workspace = true }
sp-runtime = { workspace = true }
sqlx = { workspace = true }
submerge-base = { path = "../submerge-base" }
submerge-metrics = { path = "../submerge-metrics" }
submerge-persistence = { path = "../submerge-persistence" }
submerge-substrate-client = { path = "../submerge-substrate-client" }
submerge-util = { path = "../submerge-util" }
tokio = { workspace = true }
tokio-util = { workspace = true }
tower-http = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
utoipa = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
