[package]
name = "submerge-base"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
frame-system = { workspace = true }
async-trait = { workspace = true }
cargo_metadata = { workspace = true }
clap = { workspace = true }
convert_case = { workspace = true }
hex = { workspace = true }
parity-scale-codec = { workspace = true }
rust-embed = { workspace = true }
rustc-hash = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sp-consensus-babe = { workspace = true }
sp-core = { workspace = true }
sp-runtime = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
submerge-metrics = { path = "../submerge-metrics" }
submerge-util = { path = "../submerge-util" }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
utoipa = { workspace = true }